# Generated by Django 3.2.4 on 2021-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
