# Generated by Django 3.2.4 on 2021-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_login_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCdetails',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('add_line1', models.TextField()),
                ('add_line2', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('mobile', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('idtype', models.CharField(max_length=50)),
                ('idnum', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
            ],
        ),
    ]
