# Generated by Django 3.2.4 on 2021-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_kycdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
