# Generated by Django 3.2.4 on 2021-07-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_kycdetails_acno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetails',
            name='acno',
            field=models.CharField(default='ABC202100000', max_length=12),
        ),
    ]
