# Generated by Django 3.2.4 on 2021-07-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_kycdetails_acno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetails',
            name='acno',
        ),
    ]
