# Generated by Django 3.2.4 on 2021-07-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_remove_kycdetails_acno'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='abcno',
            field=models.CharField(default='ABC202100000', max_length=12),
        ),
    ]
