# Generated by Django 3.2.4 on 2021-07-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_kycdetails_abcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='abcacc',
            fields=[
                ('abcno', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('acctype', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
