# Generated by Django 3.2.4 on 2021-08-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_abcacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateofInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofacc', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
