# Generated by Django 3.2.4 on 2021-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_rateofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateofinterest',
            name='typeofacc',
            field=models.TextField(max_length=10),
        ),
    ]
