# Generated by Django 3.2.4 on 2021-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_alter_rateofinterest_typeofacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateofinterest',
            name='typeofacc',
            field=models.TextField(),
        ),
    ]
