# Generated by Django 3.2.4 on 2021-08-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_alter_rateofinterest_typeofacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcacc',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abcacc',
            name='enddate',
            field=models.TextField(default=' '),
        ),
    ]
