# Generated by Django 3.2.4 on 2021-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20210815_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcacc',
            name='rate',
            field=models.FloatField(default=4.5),
        ),
    ]
