# Generated by Django 3.2.4 on 2021-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_abcacc_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcacc',
            name='duration',
            field=models.IntegerField(default=1825),
        ),
        migrations.AlterField(
            model_name='abcacc',
            name='enddate',
            field=models.TextField(default=''),
        ),
    ]
